### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by mrohnstock** [krokedil/klarna-payments-for-woocommerce#173]
Hi,

we're using:

Klarna Order Management for WooCommerce 1.5.0
Klarna Payments for WooCommerce 2.0.5
WooCommerce 3.8.1
Wordpress 5.3.2

with PHP 7.4.2 and receive the following error message on accessing the checkout-page:

```
PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /.../wp-content/plugins/klarna-payments-for-woocommerce/templates/klarna-payments-categories.php:14
Stack trace:
#0 /.../wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include()
#1 /.../wp-content/plugins/woocommerce/templates/checkout/payment.php(30): wc_get_template('checkout/paymen...', Array)
#2 /.../wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/...')
#3 /.../wp-content/plugins/woocommerce/includes/wc-template-functions.php(2232): wc_get_template('checkout/paymen...', Array)
#4 /.../wp-includes/class-wp-hook.php(288): woocommerce_checkout_payment('')
#5 /.../wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#6 /.../wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 ...
```

Do anyone know what the issue is...?

**Comment by mrohnstock** [comment]
well after changing the code of `templates/klarna-payments-categories.php` from

```
		$payment_category_id   = 'klarna_payments_' . $payment_category['identifier'];
		$payment_category_name = $payment_category['name'];
		$payment_category_icon = $payment_category['asset_urls']['standard'];
```

to

```
		$payment_category_id   = 'klarna_payments_' . $payment_category->identifier;
		$payment_category_name = $payment_category->name;
		$payment_category_icon = $payment_category->asset_urls->standard;
```

everything works as expected again...

**Comment by mrohnstock** [comment]
ehm... I am a bit confused, as now (after some hours) `$payment_category` is again an `array`, not an `StdClass`... so I reverted this change and everything is working again.

Really... really... strange... but it works again, so sorry for the noice.
