### ISSUE TITLE
Fatal Error when Klarna Payments is enabled in checkout

### ISSUE THREAD

**Issue by kosvrouvas** [krokedil/klarna-payments-for-woocommerce#380]
Getting this error in checkout immediately after enabling the plugin

Version 3.4.1

`Fatal error: Uncaught Error: Call to undefined method WC_GC_Cart::get_applied_gift_cards() in /home/xxxxxx/xxxxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/vendor/krokedil/woocommerce/src/Cart/Cart.php:157 Stack trace: #0 /home/thelofto/xxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/vendor/krokedil/woocommerce/src/Cart/Cart.php(44): Krokedil\WooCommerce\Cart\Cart->set_line_coupons() #1 /home/xxxxxxx/xxxxxxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/classes/requests/helpers/class-kp-order-data.php(89): Krokedil\WooCommerce\Cart\Cart->__construct(Object(WC_Cart), Array) #2 /home/xxxxxx/xxxxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/classes/requests/helpers/class-kp-order-data.php(70): KP_Order_Data->get_order_data() #3 /home/xxxx/xxxxxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/classes/class-kp-assets.php(82): KP_Order_Data->__construct('b2c', NULL) #4 /home/xxxx/xxxxxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/classes/class-kp-assets.php(48): KP_Assets->get_checkout_params(Array) #5 /home/xxxx/xxxxxxxx.gr/wp-includes/class-wp-hook.php(324): KP_Assets->enqueue_checkout_script('') #6 /home/xxxx/xxxxxxxx.gr/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #7 /home/xxxx/xxxxxxxx.gr/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #8 /home/xxxx/xxxxxxxx.gr/wp-includes/script-loader.php(2262): do_action('wp_enqueue_scri...') #9 /home/xxxx/xxxxxxxx.gr/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('') #10 /home/xxxx/xxxxxxxx.gr/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #11 /home/xxxx/xxxxxxxx.gr/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #12 /home/xxxx/xxxxxxxx.gr/wp-includes/general-template.php(3052): do_action('wp_head') #13 /home/xxxx/xxxxxxxx.gr/wp-content/themes/moren/header.php(15): wp_head() #14 /home/xxxx/xxxxxxxx.gr/wp-includes/template.php(790): require_once('/home/thelofto/...') #15 /home/xxxx/xxxxxxxx.gr/wp-includes/template.php(725): load_template('/home/thelofto/...', true, Array) #16 /home/xxxx/xxxxxxxx.gr/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #17 /home/xxxx/xxxxxxxx.gr/wp-content/themes/moren/page.php(18): get_header() #18 /home/xxxx/xxxxxxxx.gr/wp-includes/template-loader.php(106): include('/home/thelofto/...') #19 /home/xxxx/xxxxxxxx.gr/wp-blog-header.php(19): require_once('/home/thelofto/...') #20 /home/xxxx/xxxxxxxx.gr/index.php(17): require('/home/thelofto/...') #21 {main} thrown in /home/xxxx/xxxxxxxx.gr/wp-content/plugins/klarna-payments-for-woocommerce/vendor/krokedil/woocommerce/src/Cart/Cart.php on line 157`

**Comment by Ercogx** [comment]
Any updates here?

**Comment by kosvrouvas** [comment]
Any update on this? We still have this issue and Klarna is disabled because of this.

**Comment by krokedilmartin** [comment]
Hi @kosvrouvas and @Ercogx,

Are you still experiencing issues?  Could you please let us know which version of the WooCommerce Gift Cards plugin you're using?
